const tags = [
  { title: "Tarjetero", options: ["Tarjetero", "Tarjeteros"] },
  { title: "Billetera", options: ["Billetera", "Billeteras"] },
  { title: "Corbata", options: ["Corbata", "Corbatas"] },
  { title: "Corbatin", options: ["Corbatin", "Corbatins"] },
  { title: "traje de baño", options: ["traje de baño", "traje de baños"] },
  { title: "malla", options: ["malla", "mallas"] },
  { title: "playa", options: ["playa", "playas"] },
  { title: "playera", options: ["playera", "playeras"] },
  { title: "playero", options: ["playero", "playeros"] },
  { title: "bota", options: ["bota", "botas"] },
  { title: "botineta", options: ["botineta", "botinetas"] },
  { title: "borcego", options: ["borcego", "borcegos"] },
  { title: "plantas", options: ["plantas", "plantass"] },
  { title: "jungla", options: ["jungla", "junglas"] },
  { title: "gales", options: ["gales", "galess"] },
  { title: "Floreadas", options: ["Floreadas", "Floreado"] },
  { title: "perfume", options: ["perfume"] },
  { title: "Arremangado", options: ["Arremangado"] },
  { title: "Lunares", options: ["Lunares"] },
  { title: "Gris melange", options: ["Gris melange"] },
  { title: "Chaleco", options: ["chaleco"] },
  { title: "Chaleco de vestir", options: ["Chaleco de vestir"] },
  {
    title: "principe de gales",
    options: ["principe de gales", "principe de galess"],
  },
  { title: "trama", options: ["trama", "tramas"] },
  { title: "mochila", options: ["mochila", "mochilas"] },
  { title: "Boca", options: ["Boca"] },
  { title: "Letras", options: ["Letras", "Letras"] },
  { title: "Camiseta", options: ["Camiseta", "Camisetas"] },
  { title: "Dibujo", options: ["Dibujo", "Dibujos"] },
  { title: "Suelta ", options: ["Suelta ", "Sueltas"] },
  { title: "Escrito", options: ["Escrito", "Escritos"] },
  { title: "Totebag", options: ["Totebag", "Totebags"] },
  { title: "Shopbag", options: ["Shopbag", "Shopbags"] },
  { title: "Manijas", options: ["Manijas", "Manijass"] },
  { title: "Con diseño", options: ["Con diseño", "Con diseños"] },
  { title: "Manuscrito", options: ["Manuscrito", "Manuscritos"] },
  { title: "Mix", options: ["Mix"] },
  { title: "Combinación", options: ["Combinación", "Combinacións"] },
  { title: "Casual", options: ["Casual", "Casual"] },
  { title: "Dia", options: ["Dia", "Dias"] },
  { title: "Denim", options: ["Denim", "Denim"] },
  { title: "Vintage", options: ["Vintage", "Vintages"] },
  { title: "Indigo", options: ["Indigo", "Indigos"] },
  { title: "Confort", options: ["Confort", "Conforts"] },
  { title: "Prima peruano", options: ["Prima peruano", "Prima peruanos"] },
  { title: "Confortable", options: ["Confortable", "Confortables"] },
  {
    title: "Punteras metálicas",
    options: ["Punteras metálicas", "Punteras metálicass"],
  },
  {
    title: "Bolsillo delantero",
    options: ["Bolsillo delantero", "Bolsillo delanteros"],
  },
  {
    title: "Bolsillo trasero",
    options: ["Bolsillo trasero", "Bolsillo traseros"],
  },
  { title: "Suave", options: ["Suave", "Suaves"] },
  { title: "Fresco", options: ["Fresco", "Frescos"] },
  { title: "Fresca", options: ["Fresca", "Frescas"] },
  { title: "Capucha", options: ["Capucha", "Capuchas"] },
  { title: "Grande", options: ["Grande", "Grandes"] },
  { title: "Casual", options: ["Casual", "Casuals"] },
  { title: "Elastizado", options: ["Elastizado", "Elastizados"] },
  { title: "Desgastado", options: ["Desgastado", "Desgastados"] },
  { title: "Cordon", options: ["Cordon", "Cordons"] },
  { title: "Media estación", options: ["Media estación", "Media estacións"] },
  { title: "Estilo", options: ["Estilo", "Estilos"] },
  {
    title: "Calce intermedio",
    options: ["Calce intermedio", "Calce intermedios"],
  },
  { title: "Autentico", options: ["Autentico", "Autenticos"] },
  { title: "Nirvana", options: ["Nirvana", "Nirvanas"] },
  { title: "Slouchy", options: ["Slouchy", "Slouchys"] },
  {
    title: "Cintura con elástico",
    options: ["Cintura con elástico", "Cintura con elásticos"],
  },
  {
    title: "Acabado vintage",
    options: ["Acabado vintage", "Acabado vintages"],
  },
  { title: "Dobladillo", options: ["Dobladillo", "Dobladillos"] },
  { title: "Playero", options: ["Playero", "Playeros"] },
  { title: "Rigido", options: ["Rigido", "Rigidos"] },
  { title: "Comodo", options: ["Comodo", "Comodos"] },
  { title: "Boyfriend", options: ["Boyfriend", "Boyfriends"] },
  { title: "Caída suelta", options: ["Caída suelta", "Caída sueltas"] },
  { title: "Corto", options: ["Corto", "Cortos"] },
  { title: "Cintura a bota", options: ["Cintura a bota", "Cintura a botas"] },
  {
    title: "Bolsillo canguro",
    options: ["Bolsillo canguro", "Bolsillo canguros"],
  },
  {
    title: "Aspecto desgastado",
    options: ["Aspecto desgastado", "Aspecto desgastados"],
  },
  { title: "Flexible", options: ["Flexible", "Flexibles"] },
  { title: "Slimfit", options: ["Slimfit", "Slimfits"] },
  { title: "Al cuerpo", options: ["Al cuerpo", "Al cuerpos"] },
  { title: "Desflecado", options: ["Desflecado", "Desflecados"] },
  { title: "Jardinero", options: ["Jardinero", "Jardineros"] },
  { title: "Entero", options: ["Entero", "Enteros"] },
  { title: "Mono", options: ["Mono", "Monos"] },
  { title: "Tirantes", options: ["Tirantes", "Tirantess"] },
  { title: "Atemporal", options: ["Atemporal", "Atemporals"] },
  { title: "Joggin", options: ["Joggin", "Joggins"] },
  { title: "Jogger", options: ["Jogger", "Joggers"] },
  { title: "Costura", options: ["Costura", "Costuras"] },
  { title: "Batik", options: ["Batik", "Batiks"] },
  {
    title: "Algodón viscosa / viscosa",
    options: ["Algodón viscosa / viscosa", "Algodón viscosa / viscosas"],
  },
  { title: "Liviana", options: ["Liviana", "Livianas"] },
  { title: "Elegante", options: ["Elegante", "Elegantes"] },
  { title: "Baggy", options: ["Baggy", "Baggys"] },
  { title: "Gabardina ", options: ["Gabardina ", "Gabardina s"] },
  { title: "Pinzado", options: ["Pinzado", "Pinzados"] },
  { title: "Corte recto", options: ["Corte recto", "Corte rectos"] },
  {
    title: "Avios metálicos",
    options: ["Avios metálicos", "Avios metálicoss"],
  },
  { title: "Tobillero", options: ["Tobillero", "Tobilleros"] },
  { title: "Lazo ajustable", options: ["Lazo ajustable", "Lazo ajustables"] },
  { title: "Dia", options: ["Dia", "Dias"] },
  { title: "Malla", options: ["Malla", "Mallas"] },
  { title: "Traje de baño", options: ["Traje de baño", "Traje de baños"] },
  { title: "Polyester ", options: ["Polyester ", "Polyester s"] },
  { title: "Swimwear", options: ["Swimwear", "Swimwears"] },
  {
    title: "Cordon ajustable",
    options: ["Cordon ajustable", "Cordon ajustables"],
  },
  { title: "Chaqueta", options: ["Chaqueta", "Chaquetas"] },
  { title: "Hombreras", options: ["Hombreras", "Hombrerass"] },
  { title: "Elegante", options: ["Elegante", "Elegantes"] },
  { title: "Serpientes", options: ["Serpientes", "Serpientess"] },
  { title: "Men", options: ["Men", "Mens"] },
  { title: "Women", options: ["Women", "Womens"] },
  { title: "Pants", options: ["Pants", "Pantss"] },
  { title: "Enteriza", options: ["Enteriza", "Enterizas"] },
  {
    title: "Espalda abierta",
    options: ["Espalda abierta", "Espalda abiertas"],
  },
  { title: "Sexy", options: ["Sexy", "Sexys"] },
  { title: "Cavada", options: ["Cavada", "Cavadas"] },
  { title: "Atrevido", options: ["Atrevido", "Atrevidos"] },
  { title: "Shirt", options: ["Shirt", "Shirts"] },
  { title: "Sweatshirts", options: ["Sweatshirts", "Sweatshirtss"] },
  { title: "Morley", options: ["Morley", "Morleys"] },
  { title: "Acordonado", options: ["Acordonado", "Acordonados"] },
  { title: "Biker", options: ["Biker", "Bikers"] },
  { title: "Caramel", options: ["Caramel", "Caramels"] },
  { title: "Chupin", options: ["Chupin", "Chupins"] },
  {
    title: "Efecto desgastado",
    options: ["Efecto desgastado", "Efecto desgastados"],
  },
  { title: "Elvis Presley", options: ["Elvis Presley", "Elvis Presleys"] },
  { title: "Escote recto", options: ["Escote recto", "Escote rectos"] },
  { title: "Jacket", options: ["Jacket", "Jackets"] },
  {
    title: "Desconstracturado",
    options: ["Desconstracturado", "Desconstracturados"],
  },
  {
    title: "Calce slimfit holgado",
    options: ["Calce slimfit holgado", "Calce slimfit holgados"],
  },
  { title: "Tie dye", options: ["Tie dye", "Tie dyes"] },
  { title: "Elastano", options: ["Elastano", "Elastanos"] },
  { title: "Turquesa", options: ["Turquesa", "Turquesas"] },
  { title: "packs ", options: ["packs", "packss"] },
  { title: "interlock ", options: ["interlock", "interlocks"] },
  { title: "arena ", options: ["arena", "arenas"] },
  { title: "fucsia ", options: ["fucsia", "fucsias"] },
  { title: "microfibra ", options: ["microfibra", "microfibras"] },
  { title: "bordo ", options: ["bordo", "bordos"] },
  { title: "petróleo ", options: ["petróleo", "petróleos"] },
  { title: "bretel ", options: ["bretel", "bretels"] },
  { title: "interior ", options: ["interior", "interiors"] },
  { title: "termico ", options: ["termico", "termicos"] },
  { title: "calza ", options: ["calza", "calzas"] },
  { title: "calzoncillo ", options: ["calzoncillo", "calzoncillos"] },
  { title: "niños ", options: ["niños", "niñoss"] },
  { title: "remeron ", options: ["remeron", "remerons"] },
  {
    title: "manija desmontable ",
    options: ["manija desmontable", "manija desmontables"],
  },
  { title: "doble cierre ", options: ["doble cierre", "doble cierres"] },
  {
    title: "bolsillo interno ",
    options: ["bolsillo interno", "bolsillo internos"],
  },
  {
    title: "correa desmontable",
    options: ["correa desmontable", "correa desmontables"],
  },
  { title: "tachas ", options: ["tachas", "tachass"] },
  { title: "mostaza ", options: ["mostaza", "mostazas"] },
  { title: "suela ", options: ["suela", "suelas"] },
  {
    title: "bolsillo interno ",
    options: ["bolsillo interno", "bolsillo internos"],
  },
  { title: "manija corta ", options: ["manija corta", "manija cortas"] },
  {
    title: "doble compartimiento",
    options: ["doble compartimiento", "doble compartimientos"],
  },
  {
    title: "Mujer",
    options: ["mujer", "woman"],
  },
  {
    title: "Hombre",
    options: ["hombre", "man"],
  },
  {
    title: "Niño",
    options: ["niño", "boy", "niños"],
  },
  {
    title: "Niña",
    options: ["niña", "girl", "niñas"],
  },
  {
    title: "bebé",
    options: ["bebé", "bebés", "girl"],
  },
  {
    title: "holgado",
    options: ["holgado", "olgado", "olgados", "holgados"],
  },
  {
    title: "holgado",
    options: ["holgado", "olgado", "olgados", "holgados"],
  },
  {
    title: "abierto",
    options: ["abierto", "abiertos"],
  },
  {
    title: "saquito",
    options: ["saquito", "saquitos"],
  },
  {
    title: "saco",
    options: ["saco", "sacos"],
  },
  {
    title: "kimono",
    options: ["kimono", "kimonos"],
  },
  {
    title: "camisola",
    options: ["camisola", "camisolas"],
  },
  {
    title: "botones",
    options: ["botones", "boton"],
  },
  {
    title: "tunica",
    options: ["tunica", "tunicas"],
  },
  {
    title: "asimetrica",
    options: ["asimetrica", "asimetricas", "asimetrico", "asimetricos"],
  },
  {
    title: "blusa",
    options: ["blusa", "blusas"],
  },
  {
    title: "plateado",
    options: ["plateado", "plateada", "plateadas", "plateados"],
  },
  {
    title: "brilloso",
    options: ["brilloso", "brillosos", "brillosas"],
  },
  {
    title: "dorado",
    options: ["dorado", "dorados", "dorados"],
  },
  {
    title: "dorado",
    options: ["dorado", "dorados", "dorados"],
  },
  {
    title: "crudo",
    options: ["crudos", "crudo"],
  },
  {
    title: "Suelto",
    options: ["suelto", "sueltos", "suelta", "sueltas"],
  },
  {
    title: "Ajustado",
    options: ["ajustado", "ajustada", "ajustados", "ajustadas"],
  },
  {
    title: "Flores",
    options: ["flores", "floreado", "floreados", "floreada", "floreadas"],
  },
  {
    title: "ancho",
    options: ["ancho", "anchos", "ancha", "anchas"],
  },
  {
    title: "Diseño",
    options: ["diseño", "diseños", "de diseño"],
  },
  {
    title: "Remera",
    options: ["remera", "remeras", "camiseta", "camisetas"],
  },
  {
    title: "Camisa",
    options: ["camisa", "camisas"],
  },
  {
    title: "Chombas",
    options: ["chomba", "chombas"],
  },
  {
    title: "Chombas",
    options: ["chomba", "chombas"],
  },
  {
    title: "manga corta",
    options: ["manga corta", "mangas cortas"],
  },
  {
    title: "manga larga",
    options: ["manga larga", "mangas largas"],
  },
  {
    title: "manga tres cuartos",
    options: ["manga tres cuartos", "mangas tres cuartos"],
  },
  {
    title: "manga ancha",
    options: ["manga ancha", "mangas anchas"],
  },
  {
    title: "musculosa",
    options: ["musculosa", "musculosas"],
  },
  {
    title: "tiritas",
    options: ["tirita", "tiritas"],
  },
  {
    title: "top",
    options: ["top", "tops"],
  },
  {
    title: "largo",
    options: ["largo", "larga", "largos", "largas", "alargados", "alargadas"],
  },
  {
    title: "corta",
    options: ["corta", "cortas", "corto", "cortos"],
  },
  {
    title: "Escote V",
    options: ["escote v", "escotes v"],
  },
  {
    title: "cuello redondo",
    options: ["cuellos redondos", "cuello redondo"],
  },
  {
    title: "escote redondo",
    options: ["escotes redondos", "escote redondo"],
  },
  {
    title: "escote cerrado",
    options: ["escotes cerrados", "escote cerrado"],
  },
  {
    title: "polera",
    options: ["polera", "poleras"],
  },
  {
    title: "recta",
    options: ["recta", "rectas", "recto", "rectos"],
  },
  {
    title: "Hoodie",
    options: ["Hoodie", "Hoodie"],
  },

  {
    title: "estampa",
    options: [
      "estampa",
      "estampada",
      "estampadas",
      "estampas",
      "estampado",
      "estampados",
      "print",
    ],
  },
  {
    title: "punto",
    options: ["punto", "tejido", "tejidos", "tejida", "tejidas", "puntos"],
  },
  {
    title: "entallada",
    options: ["entallada", "entalladas", "entalle"],
  },
  {
    title: "rustico",
    options: ["rustico", "rustica", "rusticos", "rusticas"],
  },
  {
    title: "Palazzo",
    options: ["Palazzo", "Palazo", "Palaso"],
  },
  {
    title: "boxer",
    options: ["boxer", "boxers"],
  },
  {
    title: "mini",
    options: ["mini", "minis"],
  },
  {
    title: "Bandolera",
    options: ["Bandolera", "Bandoleras"],
  },
  {
    title: "Riñonera",
    options: ["Riñonera", "Riñoneras"],
  },

  {
    title: "Mocasines",
    options: ["Mocasines", "Mocasin"],
  },

  {
    title: "Lisos",
    options: ["Liso", "Lisos", "Lisa", "Lisas"],
  },
  {
    title: "Camison",
    options: ["Camison", "Camisones"],
  },
  {
    title: "Conjunto",
    options: ["Conjuntos", "Conjunto"],
  },
  {
    title: "Livianos",
    options: ["Livianos", "Liviano", "Liviana", "livianas"],
  },
  {
    title: "Lánguido",
    options: [
      "Lánguido",
      "Lánguidos",
      "Lánguida",
      "Lánguidas",
      "langido",
      "langidos",
      "languida",
      "languidas",
    ],
  },

  {
    title: "Rayas",
    options: ["Rayas", "Raya", "Rayado", "Rayada", "Rayados", "rayadas"],
  },
  {
    title: "Bata",
    options: ["Bata", "Batas"],
  },

  {
    title: "Elastico",
    options: ["Elastizado", "elastico", "elasticos", "elastica", "elasticas"],
  },

  {
    title: "Monoprenda",
    options: ["Monoprenda", "Monoprendas", "Mono"],
  },

  {
    title: "Bolsillo",
    options: ["Bolsillo", "bolsillos"],
  },

  {
    title: "cuadros",
    options: ["cuadros", "cuadrille"],
  },
  {
    title: "hoja",
    options: ["hojas", "hoja"],
  },
  "noche",
  "Salir",
  "Fiesta",
  "Fantasia",
  "Impermeable",
  "Set",
  "midi",
  "camel",
  "Cierre",
  "A medida",
  "Bottom",
  "animal print",
  "cebra",
  "un hombro",
  "leopardo",
  "body",
  "pride",
  "Arcoiris",
  "Oversize",
  "cuello alto",
  "Tiro alto",
  "tiro bajo",
  "tiro medio",
  "lino",
  "saten",
  "Slip",
  "seda",
  "cuerina",
  "cuero ecologico",
  "crepe",
  "lana",
  "satinado",
  "algodón",
  "spandex",
  "tul",
  "lycra",
  "gasa",
  "ropa interior",
  "cuero",
  "Legging",
  "Piel",
  "escote",
  "Termica",
  "ruana",

  "poliester",
  "Tapado",
  "Chupin",
  "Skinny",
  "Babucha",
  "Vestir",
  "gabardina",
  "puño",
  "Morley",
  "volados",
  "Rib",
  "crop",
  "pinzas",
  "baloon",
  "Verano",
  "Invierno",
  "Primavera",
  "Otoño",

  {
    title: "tacon",
    options: ["tacon", "tacones"],
  },
  {
    title: "plana",
    options: ["plana", "plano", "planas", "planos"],
  },
  {
    title: "Jersey",
    options: ["Jerseys", "Jersey"],
  },

  {
    title: "Deportivo",
    options: ["Deportivos", "deportivo", "deporte"],
  },
  {
    title: "Basica",
    options: [
      "Basica",
      "Basicas",
      "Básicas",
      "Básica",
      "basico",
      "basicos",
      "básicos",
      "básico",
    ],
  },
  {
    title: "traje",
    options: ["traje", "trajes"],
  },
  {
    title: "gastado",
    options: ["gastado", "desgaste", "desgastado", "desgastados"],
  },

  {
    title: "transparente",
    options: ["transparente", "transparentes"],
  },
  {
    title: "rotura",
    options: ["rotura", "roturas", "roto", "rotos"],
  },
  {
    title: "brillo",
    options: ["brillo", "brilloso"],
  },
  {
    title: "accesorios",
    options: ["accesorios", "accesorio"],
  },
  {
    title: "jeans",
    options: ["jean", "jeans", "denim"],
  },
  {
    title: "pijama",
    options: ["pijama", "pijamas", "piyama", "dormir"],
  },
  {
    title: "short",
    options: ["short", "shorts", "shorcito", "shorcitos", "short pollera"],
  },
  {
    title: "pollera",
    options: ["pollera", "polleras", "falda", "faldas"],
  },
  {
    title: "campera",
    options: ["campera", "camperas"],
  },
  {
    title: "buzo",
    options: ["buzo", "buzos"],
  },
  {
    title: "vestido",
    options: ["vestidos", "vestido"],
  },
  {
    title: "chaquetas y abrigos",
    options: [
      "chaquetas y abrigos",
      "abrigo",
      "abrigos",
      "sweater",
      "bomber",
      "campera denim",
      "chaqueta",
      "chaquetas",
      "blazer",
      "blazers",
      "cazadora",
    ],
  },
  {
    title: "sweater",
    options: ["sweater"],
  },
  {
    title: "cazadora",
    options: ["cazadora", "cazadoras"],
  },
  {
    title: "pantalon",
    options: [
      "pantalon",
      "pantalones",
      "calza",
      "jogger",
      "jogging",
      "joggings",
    ],
  },

  {
    title: "verde",
    options: ["verde", "verdes"],
  },
  {
    title: "militar",
    options: ["militar", "militares"],
  },
  {
    title: "oscuro",
    options: [
      "oscuro",
      "oscura",
      "oscuros",
      "obscuro",
      "obscuros",
      "oscuras",
      "obscura",
      "obscuras",
    ],
  },

  {
    title: "bermuda",
    options: ["bermuda", "bermudas"],
  },
  {
    title: "sombrero",
    options: ["sombrero", "sombreros"],
  },
  {
    title: "gorro",
    options: ["gorro", "gorros"],
  },
  {
    title: "cinturones",
    options: ["cinturones", "cinturon"],
  },
  {
    title: "pañuelo",
    options: ["pañuelo", "pañuelos"],
  },
  {
    title: "bufanda",
    options: ["bufanda", "bufandas"],
  },
  {
    title: "bolso",
    options: ["bolsos", "bolso", "bolsa", "bolsas", "mochila", "mochilas"],
  },
  {
    title: "moños",
    options: ["moños", "moño"],
  },
  {
    title: "corbatas",
    options: ["corbatas", "corbata"],
  },
  {
    title: "tapaboca",
    options: ["tapaboca", "tapabocas", "cubrebocas", "cubreboca"],
  },
  {
    title: "carteras",
    options: ["carteras", "cartera", "billeteras", "billetera"],
  },

  {
    title: "zapatos",
    options: ["zapatos", "zapato"],
  },

  {
    title: "zapatilla",
    options: ["zapatilla", "zapatillas"],
  },
  {
    title: "sandalias",
    options: ["sandalia", "sandalias"],
  },
  "alpargatas",
  "botas",
  "plataformas",
  "tacos",
  "chatitas",
  {
    title: "blanco",
    options: ["blanco", "blancos", "blancas", "blanca"],
  },
  {
    title: "negro",
    options: ["negro", "negros", "negras", "negra"],
  },
  {
    title: "azul",
    options: ["azul", "azules"],
  },
  {
    title: "gris",
    options: ["gris", "agrisado", "grices"],
  },
  {
    title: "lila",
    options: ["lila", "lilas"],
  },
  {
    title: "amarillo",
    options: ["amarillo", "amarilla", "amarillas", "amarillos"],
  },
  {
    title: "celeste ",
    options: ["celeste", "celestes"],
  },
  {
    title: "oxford",
    options: ["oxford"],
  },
  {
    title: "rojo",
    options: ["rojo", "roja", "rojas", "rojos"],
  },
  {
    title: "naranja",
    options: ["naranja", "naranjas"],
  },
  {
    title: "morado",
    options: ["morado", "morados", "morada", "moradas"],
  },
  {
    title: "marron",
    options: ["marron", "marrones"],
  },
  {
    title: "violeta",
    options: ["violeta", "violetas"],
  },
  {
    title: "magenta",
    options: ["magenta"],
  },
  {
    title: "rosa",
    options: ["rosa", "rosado", "rosada"],
  },
  {
    title: "ladrillo",
    options: ["ladrillo"],
  },
  { title: "beige", options: ["beige", "beish"] },
  { title: "Tanga", options: ["Tanga", "Tangas"] },
  { title: "Regulable", options: ["Regulable", "Regulables"] },
  { title: "Con regulación", options: ["Con regulación"] },
  { title: "Colaless", options: ["Colaless"] },
  { title: "Vedetina", options: ["Vedetina", "Vedetinas"] },
  { title: "Tangaless", options: ["Tangaless"] },
  { title: "Corpiño", options: ["Corpiño", "Corpiños"] },
  { title: "Triangulo", options: ["Triangulo", "Triangulos"] },
  { title: "Tela", options: ["Tela", "Telas"] },
  {
    title: "Corpiño ajustable",
    options: ["Corpiño ajustable", "Corpiño ajustables"],
  },
  { title: "Encaje", options: ["Encaje", "Encajes"] },
  {
    title: "Corpiño con aro",
    options: ["Corpiño con aro", "Corpiño con aros"],
  },
  { title: "Aros", options: ["Aros"] },
  { title: "Tazas", options: ["Tazas"] },
  { title: "Bombacha", options: ["Bombacha", "Bombachas"] },
  { title: "Culote", options: ["Culote", "Culotes"] },
  { title: "Culotte", options: ["Culotte", "Culottes"] },
  { title: "push up", options: ["push up"] },
  { title: "taza", options: ["taza", "tazas"] },
  { title: "almohadillas", options: ["almohadillas"] },
  { title: "blazer", options: ["blazer", "blazers"] },
  { title: "trench", options: ["trench"] },
  { title: "piloto", options: ["piloto", "pilotos"] },
  { title: "antirobo", options: ["antirobo", "antirobos"] },
  { title: "cuerina", options: ["cuerina", "cuerinas"] },
  { title: "crossbody", options: ["crossbody", "crossbodys"] },
  { title: "morral", options: ["morral", "morrales"] },
  { title: "doble uso", options: ["doble uso"] },
  { title: "simil cuero", options: ["simil cuero"] },
  {
    title: "cuero texturado",
    options: ["cuero texturado", "cueros texturados"],
  },
  { title: "ganchos", options: ["ganchos"] },
  { title: "bordado", options: ["bordado", "bordados"] },
  { title: "panal", options: ["panal", "panales"] },
  { title: "CONVERSE", options: ["CONVERSE", "CONVERSEs"] },
  { title: "DC SHOES", options: ["DC SHOES"] },
  { title: "NIKE", options: ["NIKE"] },
  { title: "ADIDAS", options: ["ADIDAS"] },
  { title: "VANS", options: ["VANS"] },
  { title: "NEW BALANCE", options: ["NEW BALANCE"] },
  { title: "chuck taylor", options: ["chuck taylor"] },
  { title: "plataforma", options: ["plataforma", "plataformas"] },

  { title: "nude", options: ["nude", "nudes"] },
  { title: "intimo", options: ["intimo", "intimos"] },
  {
    title: "lencería",
    options: ["lenceria", "lencerias", "lencería", "lencerías"],
  },
  { title: "bikini", options: ["bikini", "bikinis"] },
  { title: "comfy", options: ["comfy"] },
  { title: "housewear", options: ["housewear", "housewears"] },
  { title: "ciclista", options: ["ciclista", "ciclistas"] },
  { title: "camuflado", options: ["camuflado", "camuflados"] },
  { title: "tipografia", options: ["tipografia", "tipografias"] },
  { title: "calzado", options: ["calzado", "calzados"] },
  { title: "bomber", options: ["bomber", "bombers"] },
  { title: "piloto", options: ["piloto", "pilotos"] },
  { title: "lluvia", options: ["lluvia", "lluvias"] },
  { title: "rompeviento", options: ["rompeviento", "rompevientos"] },
  {
    title: "corte cigarette",
    options: ["corte cigarette", "corte cigarettes"],
  },
  { title: "sastrero", options: ["sastrero", "sastreros"] },
  { title: "solapa", options: ["solapa", "solapas"] },
  { title: "tira ancha", options: ["tira ancha", "tira anchas"] },
  { title: "coral", options: ["coral", "corals"] },
  { title: "minibag", options: ["minibag", "minibags"] },
  { title: "sobre", options: ["sobre", "sobres"] },
  { title: "dc", options: ["dc", "dcs"] },
  { title: "Bijou", options: ["Bijou", "Bijous"] },
  { title: "Bijouterie", options: ["Bijouterie", "Bijouteries"] },
  { title: "Collar", options: ["Collar", "Collars"] },
  { title: "Anillo", options: ["Anillo", "Anillos"] },
  { title: "Aros", options: ["Aros", "Aross"] },
  { title: "Pulsera", options: ["Pulsera", "Pulseras"] },
  { title: "Tobillera", options: ["Tobillera", "Tobilleras"] },
  { title: "Cadena", options: ["Cadena", "Cadenas"] },
  { title: "Sombrero", options: ["Sombrero", "Sombreros"] },
  { title: "Gorro", options: ["Gorro", "Gorros"] },
  { title: "Capelina", options: ["Capelina", "Capelinas"] },
  { title: "Boina", options: ["Boina", "Boinas"] },
  { title: "Visera", options: ["Visera", "Viseras"] },
  { title: "Piluso", options: ["Piluso", "Pilusos"] },
  { title: "Gorrito", options: ["Gorrito", "Gorritos"] },
  { title: "Totebag", options: ["Totebag", "Totebags"] },
  { title: "Pijama", options: ["pijama"] },
  {
    title: "Short de pijama",
    options: ["Short de pijama", "Short de pijamas"],
  },
  { title: "Cuadrillé", options: ["Cuadrillé", "Cuadrillés"] },
  { title: "Bufandon", options: ["Bufandon", "Bufandons"] },
  { title: "Lona", options: ["Lona", "Lonas"] },
  { title: "Abrigo", options: ["Abrigo", "Abrigos"] },
  { title: "Drapeado", options: ["Drapeado", "Drapeados"] },
  { title: "Chocolate", options: ["Chocolate", "Chocolates"] },
  { title: "Cocodrilo", options: ["Cocodrilo", "Cocodrilos"] },
  { title: "Gift card", options: ["Gift card", "Gift cards"] },
  { title: "Intimate", options: ["Intimate", "Intimates"] },
  {
    title: "Parte de arriba",
    options: ["Parte de arriba", "Parte de arribas"],
  },
  { title: "Parte de abajo", options: ["Parte de abajo", "Parte de abajos"] },
  { title: "Trikini", options: ["Trikini", "Trikinis"] },
  { title: "Eslabón", options: ["Eslabón", "Eslabóns"] },
  { title: "Baguette", options: ["Baguette", "Baguettes"] },
  { title: "Neon", options: ["Neon", "Neons"] },
  { title: "Visón", options: ["Visón", "Visóns"] },
  { title: "Toalla", options: ["Toalla", "Toallas"] },
  { title: "Parka", options: ["Parka", "Parkas"] },
  { title: "Colores pastel", options: ["Colores pastel", "Colores pastels"] },
  { title: "Interior", options: ["interior", " Interior forrado en tela"] },
  {
    title: "Interior forrado en simil cuero",
    options: [
      "Interior forrado en simil cuero",
      "Interior forrado en simil cueros",
    ],
  },
  {
    title: "Interior amplio",
    options: ["Interior amplio", "Interior amplios"],
  },
  { title: "Color", options: ["color", " Colores"] },
  { title: "Remache", options: ["remache", " Remaches"] },
  {
    title: "Remaches metalizados",
    options: ["Remaches metalizados", "Remaches metalizadoss"],
  },
  {
    title: "Remaches dorados",
    options: ["Remaches dorados", "Remaches doradoss"],
  },
  { title: "Cuero", options: ["cuero", " Cuero vacuno"] },
  { title: "Cuero croco", options: ["Cuero croco", "Cuero crocos"] },
  {
    title: "Cuero simil croco",
    options: ["Cuero simil croco", "Cuero simil crocos"],
  },
  { title: "Cuero charol", options: ["Cuero charol", "Cuero charols"] },
  {
    title: "Cuero simil charol",
    options: ["Cuero simil charol", "Cuero simil charols"],
  },
  { title: "Cuero floater", options: ["Cuero floater", "Cuero floaters"] },
  { title: "Correa", options: [["Correa", "Correas", "Correa"]] },
  { title: "Correa de tela", options: ["Correa de tela", "Correa de telas"] },
  {
    title: "Correa regulable",
    options: ["Correa regulable", "Correa regulables"],
  },
  {
    title: "Correa intercambiable",
    options: ["Correa intercambiable", "Correa intercambiables"],
  },
  { title: "Correa larga", options: ["Correa larga", "Correa largas"] },
  { title: "Correa corta", options: ["Correa corta", "Correa cortas"] },
  { title: "Correa cadena", options: ["Correa cadena", "Correa cadenas"] },
  {
    title: "Correa trenzada",
    options: ["Correa trenzada", "Correa trenzadas"],
  },
  {
    title: "Correa ajustable",
    options: ["Correa ajustable", "Correa ajustables"],
  },
  { title: "Doble correa", options: ["Doble correa", "Doble correas"] },
  { title: "Hebilla", options: ["hebilla", " Hebillas"] },
  {
    title: "Hebilla niquelada",
    options: ["Hebilla niquelada", "Hebilla niqueladas"],
  },
  {
    title: "Hebilla para regular",
    options: ["Hebilla para regular", "Hebilla para regulars"],
  },
  { title: "Manija", options: ["manija", " Manijas"] },
  { title: "Manijas cortas", options: ["Manijas cortas", "Manijas cortass"] },
  { title: "Manijas largas", options: ["Manijas largas", "Manijas largass"] },
  {
    title: "Manijas desmontables",
    options: ["Manijas desmontables", "Manijas desmontabless"],
  },
  {
    title: "Manijas regulables",
    options: ["Manijas regulables", "Manijas regulabless"],
  },
  {
    title: "Manijas con herrajes",
    options: ["Manijas con herrajes", "Manijas con herrajess"],
  },
  { title: "Bolsillo", options: [["Bolsillos", "Bolsillo"]] },
  {
    title: "Bolsillo interno con cierre",
    options: ["Bolsillo interno con cierre", "Bolsillo interno con cierres"],
  },
  {
    title: "Bolsillo externo con cierre",
    options: ["Bolsillo externo con cierre", "Bolsillo externo con cierres"],
  },
  {
    title: "Bolsillos internos",
    options: ["Bolsillos internos", "Bolsillos internoss"],
  },
  {
    title: "Bolsillos externos",
    options: ["Bolsillos externos", "Bolsillos externoss"],
  },
  {
    title: "Bolsillo profundo",
    options: ["Bolsillo profundo", "Bolsillo profundos"],
  },
  {
    title: "Bolsillos delanteros",
    options: ["Bolsillos delanteros", "Bolsillos delanteross"],
  },
  {
    title: "Bolsillos traseros",
    options: ["Bolsillos traseros", "Bolsillos traseross"],
  },
  {
    title: "Bolsillos laterales",
    options: ["Bolsillos laterales", "Bolsillos lateraless"],
  },
  {
    title: "Bolsillos externos",
    options: ["Bolsillos externos", "Bolsillos externoss"],
  },
  {
    title: "Cinco bolsillos",
    options: ["Cinco bolsillos", "Cinco bolsilloss"],
  },
  {
    title: "Bolsillo abierto",
    options: ["Bolsillo abierto", "Bolsillo abiertos"],
  },
  {
    title: "Bolsillo con cierre",
    options: ["Bolsillo con cierre", "Bolsillo con cierres"],
  },
  {
    title: "Bolsillo para celular",
    options: ["Bolsillo para celular", "Bolsillo para celulars"],
  },
  {
    title: "Multiples bolsillos",
    options: ["Multiples bolsillos", "Multiples bolsilloss"],
  },
  { title: "Cinturon", options: [[" Cinturones", "Cinturon"]] },
  {
    title: "Cinturones con herrajes",
    options: ["Cinturones con herrajes", "Cinturones con herrajess"],
  },
  { title: "Boton", options: [[" Botones", "Boton"]] },
  {
    title: "Botones con iman",
    options: ["Botones con iman", "Botones con imans"],
  },
  {
    title: "Botones metalicos",
    options: ["Botones metalicos", "Botones metalicoss"],
  },
  {
    title: "Botones imantados",
    options: ["Botones imantados", "Botones imantadoss"],
  },
  { title: "Abotonado", options: ["Abotonado", "Abotonados"] },
  { title: "Boton imantado", options: ["Boton imantado", "Boton imantados"] },
  { title: "Cierre", options: [[" Cierres", "Cierre"]] },
  {
    title: "Cierres delanteros",
    options: ["Cierres delanteros", "Cierres delanteross"],
  },
  {
    title: "Cierres traseros",
    options: ["Cierres traseros", "Cierres traseross"],
  },
  {
    title: "Cierres laterales",
    options: ["Cierres laterales", "Cierres lateraless"],
  },
  {
    title: "Cierre diagonal",
    options: ["Cierre diagonal", "Cierre diagonals"],
  },
  {
    title: "Cierre plateado",
    options: ["Cierre plateado", "Cierre plateados"],
  },
  { title: "Cierre dorado", options: ["Cierre dorado", "Cierre dorados"] },
  { title: "Cierre cobre", options: ["Cierre cobre", "Cierre cobres"] },
  {
    title: "Cierre metalizado",
    options: ["Cierre metalizado", "Cierre metalizados"],
  },
  {
    title: "Cierre imantado",
    options: ["Cierre imantado", "Cierre imantados"],
  },
  {
    title: "Cierre con velcro",
    options: ["Cierre con velcro", "Cierre con velcros"],
  },
  {
    title: "Cierre con giro",
    options: ["Cierre con giro", "Cierre con giros"],
  },
  { title: "Cierre niquel", options: ["Cierre niquel", "Cierre niquels"] },
  {
    title: "Cierre para acceso",
    options: ["Cierre para acceso", "Cierre para accesos"],
  },
  { title: "Metalizado", options: [[" cierre con giro dorado", "Metalizado"]] },
  {
    title: "Plantilla anatómica",
    options: ["Plantilla anatómica", "Plantilla anatómicas"],
  },
  { title: "Horma normal", options: ["Horma normal", "Horma normals"] },
  { title: "Estilo", options: [[" Estilo urbano", "Estilo"]] },
  {
    title: "Estilo motoquera",
    options: ["Estilo motoquera", "Estilo motoqueras"],
  },
  { title: "Estilo rocker", options: ["Estilo rocker", "Estilo rockers"] },
  { title: "Estilo sporty", options: ["Estilo sporty", "Estilo sportys"] },
  { title: "Abrojo", options: ["Abrojo", "Abrojos"] },
  {
    title: "Guantera interna",
    options: ["Guantera interna", "Guantera internas"],
  },
  { title: "Culote less", options: ["Culote less", "Culote lesss"] },
  { title: "Puntilla", options: ["Puntilla", "Puntillas"] },
  { title: "Arco", options: ["Arco", "Arcos"] },
  { title: "Strapless", options: ["Strapless", "Straplesss"] },
  { title: "Pocket", options: ["Pocket", "Pockets"] },
  { title: "Camuflado", options: ["Camuflado", "Camuflados"] },
  { title: "Tipografía", options: ["Tipografía", "Tipografías"] },
  { title: "Bomber", options: ["Bomber", "Bombers"] },
  { title: "Piloto", options: ["Piloto", "Pilotos"] },
  { title: "Lluvia", options: ["Lluvia", "Lluvias"] },
  { title: "Rompeviento", options: ["Rompeviento", "Rompevientos"] },
  { title: "Corte", options: [[" Corte acampanado", "Corte"]] },
  {
    title: "Corte cigarette",
    options: ["Corte cigarette", "Corte cigarettes"],
  },
  {
    title: "Corte tobillero",
    options: ["Corte tobillero", "Corte tobilleros"],
  },
  { title: "Corte Mom", options: ["Corte Mom", "Corte Moms"] },
  {
    title: "Corte Boyfriend",
    options: ["Corte Boyfriend", "Corte Boyfriends"],
  },
  { title: "Medias", options: ["Medias", "Mediass"] },
  { title: "Soquetes", options: ["Soquetes", "Soquetess"] },
  { title: "Calcetines", options: ["Calcetines", "Calcetiness"] },
  { title: "Media pierna", options: ["Media pierna", "Media piernas"] },
  { title: "Crema", options: ["Crema", "Cremas"] },
  { title: "Tiza", options: ["Tiza", "Tizas"] },
  { title: "Metalizada", options: ["Metalizada", "Metalizadas"] },
  { title: "Combinada", options: ["Combinada", "Combinadas"] },
  { title: "Con detalles", options: ["Con detalles", "Con detalless"] },
  { title: "Details", options: ["Details", "Detailss"] },
  { title: "Flecos", options: ["Flecos", "Flecoss"] },
  { title: "Lentes", options: ["Lentes", "Lentess"] },
  { title: "gafas", options: ["gafas", "gafass"] },
  { title: "anteojos", options: ["anteojos", "anteojoss"] },
  { title: "Teen", options: ["Teen", "Teens"] },
  { title: "Gomita de pelo", options: ["Gomita de pelo", "Gomita de pelos"] },
  { title: "Scrunchie", options: ["Scrunchie", "Scrunchies"] },
  { title: "Choker", options: ["Choker", "Chokers"] },
  { title: "Herraje", options: [[" Herrajes", "Herraje"]] },
  {
    title: "Herrajes metalizados",
    options: ["Herrajes metalizados", "Herrajes metalizadoss"],
  },
  {
    title: "Herrajes dorados",
    options: ["Herrajes dorados", "Herrajes doradoss"],
  },
  {
    title: "Herrajes niquelados",
    options: ["Herrajes niquelados", "Herrajes niqueladoss"],
  },
  { title: "Tela", options: [[" Mix de telas", "Tela"]] },
  { title: "Tela de avion", options: ["Tela de avion", "Tela de avions"] },
  { title: "Tela lurex", options: ["Tela lurex", "Tela lurexs"] },
  { title: "Tela Nylon", options: ["Tela Nylon", "Tela Nylons"] },
  { title: "Tela acrílico", options: ["Tela acrílico", "Tela acrílicos"] },
  {
    title: "Tela impermeable",
    options: ["Tela impermeable", "Tela impermeables"],
  },
  {
    title: "Tela metalizada",
    options: ["Tela metalizada", "Tela metalizadas"],
  },
  {
    title: "Tela holográfica",
    options: ["Tela holográfica", "Tela holográficas"],
  },
  {
    title: "Tela con lentejuelas",
    options: ["Tela con lentejuelas", "Tela con lentejuelass"],
  },
  { title: "Tela combinada", options: ["Tela combinada", "Tela combinadas"] },
  { title: "Tela tie dye", options: ["Tela tie dye", "Tela tie dyes"] },
  { title: "Tela sublimada", options: ["Tela sublimada", "Tela sublimadas"] },
  { title: "Tela velvet", options: ["Tela velvet", "Tela velvets"] },
  { title: "Tela gamuza", options: ["Tela gamuza", "Tela gamuzas"] },
  {
    title: "Tela simil gamuza",
    options: ["Tela simil gamuza", "Tela simil gamuzas"],
  },
  { title: "Tela lavada", options: ["Tela lavada", "Tela lavadas"] },
  { title: "Tela neoprene", options: ["Tela neoprene", "Tela neoprenes"] },
  {
    title: "Tela simil neoprene",
    options: ["Tela simil neoprene", "Tela simil neoprenes"],
  },
  { title: "Tela engomada", options: ["Tela engomada", "Tela engomadas"] },
  { title: "Tela charol", options: ["Tela charol", "Tela charols"] },
  { title: "Tela sire", options: ["Tela sire", "Tela sires"] },
  { title: "Tela de lona", options: ["Tela de lona", "Tela de lonas"] },
  {
    title: "Tela de gabardina",
    options: ["Tela de gabardina", "Tela de gabardinas"],
  },
  {
    title: "Tela de corderoy",
    options: ["Tela de corderoy", "Tela de corderoys"],
  },
  { title: "Corderoy", options: ["Corderoy", "Corderoys"] },
  { title: "Lona", options: ["Lona", "Lonas"] },
  { title: "Lurex", options: ["Lurex", "Lurexs"] },
  { title: "Lentejuelas", options: ["Lentejuelas", "Lentejuelass"] },
  { title: "Sublimado", options: ["Sublimado", "Sublimados"] },
  { title: "Holográfico", options: ["Holográfico", "Holográficos"] },
  { title: "Velvet", options: ["Velvet", "Velvets"] },
  { title: "Lavado", options: ["Lavado", "Lavados"] },
  { title: "Gamuza", options: ["Gamuza", "Gamuzas"] },
  { title: "Neoprene", options: ["Neoprene", "Neoprenes"] },
  { title: "Simil neoprene", options: ["Simil neoprene", "Simil neoprenes"] },
  { title: "Acrílico", options: ["Acrílico", "Acrílicos"] },
  { title: "Tie dye", options: ["Tie dye", "Tie dyes"] },
  { title: "Engomado", options: ["Engomado", "Engomados"] },
  { title: "Zebra", options: ["Zebra", "Zebras"] },
  { title: "Tajo", options: [[" Tajo frontal", "Tajo"]] },
  { title: "Tajo lateral", options: ["Tajo lateral", "Tajo  laterals"] },
  { title: "Tazas lencero", options: ["Tazas lencero", "Tazas lenceros"] },
  { title: "Irregular", options: ["Irregular", "Irregulars"] },
  { title: "Falda", options: ["Falda", "Faldas"] },
  { title: "No gender", options: ["No gender", "No genders", "nogender"] },
  { title: "Teen", options: ["Teen", "Teens"] },
  { title: "Amplio", options: ["Amplio", "Amplios"] },
  { title: "Cinto", options: ["Cinto", "Cintos"] },
  { title: "Nudo", options: ["Nudo", "Nudos"] },
  { title: "Lateral", options: ["Lateral", "Laterals"] },
  { title: "Sin mangas", options: ["Sin mangas", "Sin mangass"] },
  { title: "Básico", options: ["Básico", "Básicos"] },
  { title: "Bretel", options: [[" Breteles", "Bretel"]] },
  {
    title: "Largo a la cadera",
    options: ["Largo a la cadera", "Largo a la caderas"],
  },
  { title: "Calado", options: ["Calado", "Calados"] },
  { title: "Tejido", options: ["Tejido", "Tejidos"] },
  { title: "Frunce", options: ["Frunce", "Frunces"] },
  { title: "Clásica", options: ["Clásica", "Clásicas"] },
  { title: "Blanco y negro", options: ["Blanco y negro", "Blanco y negros"] },
  { title: "Suela de goma", options: ["Suela de goma", "Suela de gomas"] },
  { title: "Tira", options: ["Tira", "Tiras"] },
  { title: "Tiras", options: ["Tiras", "Tirass"] },
  {
    title: "Tiras intercambiables",
    options: ["Tiras intercambiables", "Tiras intercambiabless"],
  },
  { title: "Tiras de tela", options: ["Tiras de tela", "Tiras de telas"] },
  {
    title: "Tiras ajustables",
    options: ["Tiras ajustables", "Tiras ajustabless"],
  },
  {
    title: "Tiras desmontables",
    options: ["Tiras desmontables", "Tiras desmontabless"],
  },
  {
    title: "Tiras regulables",
    options: ["Tiras regulables", "Tiras regulabless"],
  },
  { title: "Matelaseado", options: ["Matelaseado", "Matelaseados"] },
  { title: "Lona raso", options: ["Lona raso", "Lona rasos"] },
  { title: "Velcro", options: ["Velcro", "Velcros"] },
  { title: "Broche", options: ["Broche", "Broches"] },
  { title: "Broches", options: ["Broches", "Brochess"] },
  {
    title: "Broche niquelado",
    options: ["Broche niquelado", "Broche niquelados"],
  },
  {
    title: "Broches metalizados",
    options: ["Broches metalizados", "Broches metalizadoss"],
  },
  {
    title: "Broche imantado",
    options: ["Broche imantado", "Broche imantados"],
  },
  {
    title: "Broche giratorio",
    options: ["Broche giratorio", "Broche giratorios"],
  },
  { title: "Gancho", options: ["Gancho", "Ganchos"] },
  { title: "Ganchos", options: ["Ganchos", "Ganchoss"] },
  {
    title: "Gancho metalizado",
    options: ["Gancho metalizado", "Gancho metalizados"],
  },
  {
    title: "Ganchos metalizados",
    options: ["Ganchos metalizados", "Ganchos metalizadoss"],
  },
  {
    title: "Gancho con porta llaves",
    options: ["Gancho con porta llaves", "Gancho con porta llavess"],
  },
  {
    title: "Gancho con sujetador desmontable",
    options: [
      "Gancho con sujetador desmontable",
      "Gancho con sujetador desmontables",
    ],
  },
  {
    title: "Gancho niquelado",
    options: ["Gancho niquelado", "Gancho niquelados"],
  },
  {
    title: "Gancho con sujetador de mano",
    options: ["Gancho con sujetador de mano", "Gancho con sujetador de manos"],
  },
  { title: "Porta", options: ["Porta", "Portas"] },
  { title: "Porta celular", options: ["Porta celular", "Porta celulars"] },
  { title: "Porta llaves", options: ["Porta llaves", "Porta llavess"] },
  {
    title: "Portacosmeticos",
    options: ["Portacosmeticos", "Portacosmeticoss"],
  },
  { title: "Porta barbijo", options: ["Porta barbijo", "Porta barbijos"] },
  { title: "Porta brochas", options: ["Porta brochas", "Porta brochass"] },
  { title: "Lurex", options: ["Lurex", "Lurexs"] },
  { title: "Gemelos", options: ["Gemelos", "Gemeloss"] },
  { title: "Tiradores", options: ["Tiradores", "Tiradoress"] },
  { title: "Translúcido", options: ["Translúcido", "Translúcidos"] },
  { title: "Multicolor", options: ["Multicolor", "Multicolors"] },
  { title: "Strass", options: ["Strass", "Strasss"] },
  { title: "Colgante", options: ["Colgante", "Colgantes"] },
  { title: "Níquel", options: ["Níquel", "Níquels"] },
  { title: "Plisado", options: ["Plisado", "Plisados"] },
  { title: "Vincha", options: ["Vincha", "Vinchas"] },
  { title: "Fluo", options: ["Fluo", "Fluos"] },
  { title: "Montgomery", options: ["Montgomery", "Montgomerys"] },
  { title: "Coat", options: ["Coat", "Coats"] },
  { title: "Pelo sintético", options: ["Pelo sintético", "Pelo sintéticos"] },
  { title: "Red", options: ["Red", "Reds"] },
  { title: "Cartuchera", options: ["Cartuchera", "Cartucheras"] },
  { title: "Glitter", options: ["Glitter", "Glitters"] },
  { title: "Chancletas", options: ["Chancletas", "Chancletass"] },
  { title: "Ojotas", options: ["Ojotas", "Ojotass"] },
  { title: "Estuche", options: ["Estuche", "Estuches"] },
  {
    title: "Cadena para barbijo",
    options: ["Cadena para barbijo", "Cadena para barbijos"],
  },
  { title: "Giftcard", options: ["Giftcard", "Giftcards"] },
  { title: "Pastel", options: ["Pastel", "Pastels"] },
  { title: "computadora", options: [["computadora", "computadora"]] },
  { title: "laptop", options: ["laptop", "laptops"] },
  { title: "Tiracierres", options: ["Tiracierres", "Tiracierress"] },
  { title: "Charol", options: ["Charol", "Charols"] },
  { title: "Cierre interno", options: ["Cierre interno", "Cierre internos"] },
  { title: "Trenzado", options: ["Trenzado", "Trenzados"] },
  { title: "Rigida", options: ["Rigida", "Rigidas"] },
  { title: "Semi rigida", options: ["Semi rigida", "Semi rigidas"] },
  {
    title: "Estructura blanda",
    options: ["Estructura blanda", "Estructura blandas"],
  },
  { title: "Kaki guantera", options: ["Kaki guantera", "Kaki guanteras"] },
  { title: "Larga", options: ["Larga", "Largas"] },
  { title: "Cremallera", options: ["Cremallera", "Cremalleras"] },
  { title: "Monedero", options: ["Monedero", "Monederos"] },
  { title: "Desmontable", options: ["Desmontable", "Desmontables"] },
  {
    title: "Costuras visibles",
    options: ["Costuras visibles", "Costuras visibless"],
  },
  { title: "Compartimentos", options: ["Compartimentos", "Compartimentoss"] },
  { title: "Plus Size", options: ["Plus Size", "Plus Sizes"] },
  {
    title: "amplia curva de talles",
    options: ["amplia curva de talles", "amplia curva de talless"],
  },
];

const fullTags = tags.map((tag) => {
  if (tag.title) {
    let newTag = {
      title: tag.title.toLowerCase().trim(),
      options: tag.options.flat().map((tagItem) => {
        return tagItem.toLowerCase().trim();
      }),
    };
    return newTag;
  } else {
    return {
      title: tag.toLowerCase().trim(),
      options: [tag.toLowerCase().trim()],
    };
  }
});

module.exports = fullTags;
